//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Tienda_Malena.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Productos()
        {
            this.Factura = new HashSet<Factura>();
            this.Review = new HashSet<Review>();
        }
    
        public int ID_Producto { get; set; }
        public Nullable<int> ID_Categoria { get; set; }
        public Nullable<int> ID_Marca { get; set; }
        public string Nombre_Producto { get; set; }
        public byte[] Imagen_Producto { get; set; }
        public string Descripcion_Producto { get; set; }
        public Nullable<int> Stock { get; set; }
        public Nullable<int> Precio { get; set; }
        public Nullable<int> Descuento { get; set; }
        public Nullable<bool> Destacado { get; set; }
    
        public virtual Categorias Categorias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Factura> Factura { get; set; }
        public virtual Marcas Marcas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Review> Review { get; set; }
    }
}
